### PR TITLE
Fixes the Assets' class handling of missing locales by implementing fallback locales.

### LINKED ISSUE #38: Asset get() methods can throw Uncaught Exceptions when the content model is non-localized
`Asset` methods such as `getFile()` and `getTitle()` can throw uncaught exceptions when the `Asset` in question has `localized` property set to `false`.

For example, say i have the regular `DynamicEntry` - `Car`, with a linked field `Image`, which is an `Asset`.

Let's say the `Image` looks like this:

```json
  {
    "name": "Image",
    "id": "image",
    "type": "Link",
    "linkType": "Asset",
    "validations": [],
    "localized": false,
    "required": false,
    "disabled": false,
    "omitted": false
  }
```

Now, if you attempt to `getTitle('fr')` on this `Asset` for example, the SDK will throw:

`Undefined property: stdClass::$fr`

I'd suggest the expected behaviour in this scenario should be fallback to the default value.

### PR DESCRIPTION
**Pull request by realityking**
Fixes #38

### CODE REVIEW

File: tests/Unit/Delivery/AssetTest.php [hunk 1]
```diff
@@ -85,6 +91,42 @@ public function testGetter()
         $this->assertEquals(new \DateTimeImmutable('2013-09-02T14:56:34.240Z'), $asset->getUpdatedAt());
     }
 
+    public function testGetTitleWithLocale()
+    {
+        $asset = $this->asset;
+
+        $this->assertEquals('Nyan Cat', $asset->getTitle());
+        $this->assertEquals('Nyan Cat', $asset->getTitle('en-US'));
+        $this->assertEquals('Nyan Cat', $asset->getTitle('tlh'));
```
Comment (loudmouth) [inline tests/Unit/Delivery/AssetTest.php]: should we add a test case that has a different expected value other than `'Nyan Cat'` i.e. a translated title?

Comment (realityking) [inline tests/Unit/Delivery/AssetTest.php]: Good point, let me change the tests.

**Comment by realityking** [comment]
@loudmouth could you have another look?
